### ISSUE TITLE
Release gst1-java-core in a maven repo

### ISSUE THREAD

**Issue by smarquard** [gstreamer-java/gst1-java-core#12]
gst1-java-core needs a release in a maven repo so that other projects can list it as a dependency.

Ideally an initial point release (e.g. gst1-java-core-0.90), and then possibly -SNAPSHOT releases periodically for testing.

This needs updates to the pom.xml file:

https://groups.google.com/forum/#!topic/gstreamer-java/SDIwAJD2vHU

**Comment by bwulff** [comment]
We put this into our own public repo, I can set one up tomorrow.

But I think it would be better to place the artifact one of the well-known public repos like maven central. There is a guide to publishing artifacts on central: 

https://maven.apache.org/guides/mini/guide-central-repository-upload.html

I can help with both.

**Comment by neilcsmith-net** [comment]
Thanks @bwulff 

This pull request from the 0.10 bindings is probably useful info too - https://github.com/gstreamer-java/gstreamer-java/pull/150

**Comment by knightpop** [comment]
@neilcsmith-net When will you upload to maven?

**Comment by neilcsmith-net** [comment]
@knightpop - soon, when we're ready to have releases ... which is probably now.

@sarxos - thanks, yes I set up a Sonatype account the other week in order to progress this. The `org.freedesktop.gstreamer` group ID would be ideal, but that likely involves us being semi-official with GStreamer.  As you say, the fallback option is `com.github.gstreamer-java`, although I'm not keen on the location of the code repository determining this.

Neither of the group ID's of 0.10 are any use.  That originally used `org.gstreamer` which is owned by someone unconnected with GStreamer (that's why GStreamer uses freedesktop!), and the recent group ID is `com.googlecode.gstreamer-java`.

Incidentally, I repackaged under `org.freedesktop.gstreamer` when updating the bindings for 1.x to better allow for parallel usage.

**Comment by lfarkas** [comment]
i'd prefer org.freedesktop.gstreamer.

**Comment by knightpop** [comment]
@neilcsmith-net Thanks, please ping me when done, and you have some time to ping me... I`m really looking forward..

And do you have any interest of scala? I use your library from scala. If you want to build, I can help!

**Comment by neilcsmith-net** [comment]
@lfarkas of course!  However, that's not up to us.  Do you (or anyone else) have a contact within the GStreamer project who could help out with that?  If not, I'll try and make contact.

@knightpop yes, we'll ping you.  I personally have no interest in Scala, but glad to know it's working for you there :smile: What's the project out of interest - would be good to get a list together sometime - hmm, off-topic for this issue though.  If you're not on it, sign up to the Google Groups list - https://groups.google.com/forum/#!forum/gstreamer-java

**Comment by sarxos** [comment]
@neilcsmith-net, 

The package name does not have to correlate with group ID. These can be completely different, but people usually use the same for both.

@lfarkas, 

In regards to which group ID can be used, Sonatype [describes](http://central.sonatype.org/pages/choosing-your-coordinates.html) group ID as:

> it reuses the domain name system in a reversed manner. This means that if you are controlling a domain name you can use any groupId starting with the reverse domain name and subsections and create as many as you desire

That means if you have control over the domain gstreamer.freedesktop.org, you can use group ID created from it (namely org.freedesktop.gstreamer). That probably means that gstreamer-java need to have acceptance from a GStreamer project maintainer to use their domain as a group ID, or rather, that probably GStreamer maintainer would have to be the one who have create ticket in OSSHR JIRA to gain access to group ID and provide login names of the people who should also be granted with release privileges.

If project cannot use ```org.freedesktop.gstreamer```group ID then I would simply use the recent one, i.e. ```com.googlecode.gstreamer-java``` but with the unchanged package name, i.e. ```org.freedesktop.gstreamer```. There is no conflict here since package and group ID can be different. It's common practice to use historical artifact coordinates, e.g. commons-io uses the same artifact and group ID (namely commons-io) over the years, but the package name is ```org.apache.commons.io```. I personally released artifacts which has my own group ID com.github.sarxos, but had completely different package names in the JARs.

**Comment by neilcsmith-net** [comment]
I understand that package name and group ID don't have to correlate, just rather they did if we can.  Makes searching easier, and I'd rather not have the code's current location determine its group ID. The other option is probably sorting out a domain.

Keeping use of `com.googlecode.gstreamer-java` for group ID makes sense for the legacy 0.10 bindings, but not for this project IMO.

**Comment by lfarkas** [comment]
I don't have contact with gstreamer project but imho they will accept it immediately:-)

**Comment by sarxos** [comment]
I also think this it is doable but we won't know unless we try ;P

**Comment by lafoletc** [comment]
Has an official version been planned ?

**Comment by neilcsmith-net** [comment]
Yes, sorry about the delay - not had much time for this project earlier in the year due to other work (this has now changed - I'll be working on projects using the bindings most of the time for the rest of the year!).

I'm in the middle of conversations with upstream GStreamer people about using their domain as Maven coordinates.  Positive, but not quite "accept immediately" :smile: Will keep this issue up-to-date.

**Comment by lafoletc** [comment]
hello Neil,
I will use gstreamer-java in an industrial project : 
- my security department will need an official release to check and accept the COTS
- can we make a filter on pending pull requests ?
- what can I do to accelerate the release ?
Regards

**Comment by neilcsmith-net** [comment]
Hi @lafoletc - good to know - be interested to find out more - away from this issue obviously.

I've been tied up with a few things the last couple of weeks but am already planning to chase up GStreamer people on this next week.  One way or another I'll aim to get the group ID sorted by the end of next week, and a 0.9 release up ASAP after that.

Do your security department specifically require Maven - can do a tagged release here if any use?

What do you mean by filter on pending pull requests?

Nothing immediate to do to accelerate the release, but the other thing I'll be doing next week is setting up a roadmap towards 1.0.  I'll be opening the discussion on that on the mailing list.

Best wishes, Neil

**Comment by lafoletc** [comment]
Hi Neil,
if the release could be put in a maven repository before end of July, it would be great.
for pull requests : 
- https://github.com/gstreamer-java/gst1-java-core/pull/65 and https://github.com/gstreamer-java/gst1-java-core/pull/67 could be accepted ?
- https://github.com/gstreamer-java/gst1-java-core/pull/61 just avoids nullPointerException
- if https://github.com/gstreamer-java/gst1-java-core/pull/61 is accepted, https://github.com/gstreamer-java/gst1-java-core/pull/62 too
If someone wants to pull another resquest before the release ....
Regards

**Comment by neilcsmith-net** [comment]
FYI - OK from GStreamer and request in process at Sonatype https://issues.sonatype.org/browse/OSSRH-32434

If you can address the comments in #61 (either type mapper, or (simpler) check with `Pointer.NULL` and add a `//@TODO handle in type mapper`) then I'll pull those in prior to any release. Thanks.

**Comment by lafoletc** [comment]
comments modified in #61

**Comment by neilcsmith-net** [comment]
Just a quick follow up - getting set up with Sonatype is taking a little longer than I hoped.  One issue is them clarifying with upstream GStreamer on use of the group ID.  The other issue is that they want to give permission to use the org.freedesktop group ID because that already exists - I've made the point that that's a little like giving everyone access to com.github but we can work with it if need be.

**Comment by neilcsmith-net** [comment]
Right, access to `org.freedesktop` has been granted.  I've also finally got around to pushing a `jaudiolibs.org` project to central to get my head around this Maven release lark! :smile: Our `POM` needs a few changes, and I want to check building against latest JNA, but other than that we should be good to go with the first `0.9.0` release. Speak up if the current state of the repo is missing anything urgent!

**Comment by neilcsmith-net** [comment]
Added pull request for POM changes (and JNA fix). #71 Please have a look before I merge.

To test it, I actually made a SNAPSHOT release - https://oss.sonatype.org/content/repositories/snapshots/org/freedesktop/gstreamer/  Please check building against it.

**Comment by neilcsmith-net** [comment]
OK, no one commented!  Release 0.9.0 has been pushed to central. Onwards to 0.9.1.  Thanks everyone! :smile:

**Comment by smarquard** [comment]
Excellent, thank you!

**Comment by smarquard** [comment]
Noting the maven co-ordinates here for future reference:

````
<dependency>
       <groupId>org.freedesktop.gstreamer</groupId>
       <artifactId>gst1-java-core</artifactId>
       <version>0.9.0</version>
</dependency>
````

https://oss.sonatype.org/content/repositories/releases/org/freedesktop/gstreamer/gst1-java-core/0.9.0/

**Comment by lafoletc** [comment]
thank you!
