### ISSUE TITLE
Problem closing rtsp pipelines

### ISSUE THREAD

**Issue by manojnirala** [gstreamer-java/gst1-java-core#218]
Dear All,

I am building a java application which reads from an IP camera as video source. The gstreamer pipeline works fine while it is playing, but is not closing properly. I get the following error message(s) when I try to do either pipe.pause( ) or pipe.stop( ):

busMessage >>> GstMessageProgress, type=(GstProgressType)GST_PROGRESS_TYPE_START, code=(string)request, text=(string)"Sending\ PAUSE\ request", percent=(int)0, timeout=(int)-1;
 busMessage >>> GstMessageProgress, type=(GstProgressType)GST_PROGRESS_TYPE_CONTINUE, code=(string)request, text=(string)"Sending\ PAUSE\ request", percent=(int)0, timeout=(int)-1;

busMessage >>> GstMessageError, gerror=(GError)NULL, debug=(string)"gstrtspsrc.c\(6157\):\ gst_rtspsrc_send\ \(\):\ /GstPipeline:pipeline1/GstRTSPSrc:videoSrc:\012Option\ not\ supported\ \(551\)", details=(structure)"details\,\ rtsp-status-code\=\(uint\)551\,\ rtsp-status-reason\=\(string\)\"Option\\\ not\\\ supported\"\;";
 Error >>> Bin: [videoSrc] : Unhandled error
 Error >>> Bin: [videoSrc] : Could not write to resource.

My understanding of closing pipelines is derived from how we close ksvideosrc pipelines. Clearly, IP cameras form a different use case. Could any one please offer us an example on how to properly close/pause IP cameras (rtspsrc) pipelines? We would also like to have a re-start button which should restart the pipeline after being paused. So clearing the pipeline entirely is not a solution that we are looking for.

Thank you,
Best Regards,
Manoj

**Comment by neilcsmith-net** [comment]
Please keep all requests for (free) support on the mailing list. Only use the issue queue for actual issues or feature requests, thanks.  If this turns out to be an issue with the bindings, or something missing that you need access to, please open another issue. We ( [Codelerity](https://www.codelerity.com) ) can also provide commercial support, but at this stage your best bet is probably checking against examples upstream or for other languages.
